name: Check code with Ktlint

on:
  push:
    branches:
      - '!master'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Administratice permission
        run: ./gradlew chmod +x gradlew

      - name: Run ktlint
        run: ./gradlew ktlint
