name: Check code with Ktlint

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Grant executive permission
        run: chmod +x gradlew

      - name: Run ktlint
        run: ./gradlew ktlint
